MS-Toys/Controllers/LogInController.cs
using MS_Toys.Models;
using StoreAdministration;
using System.Diagnostics;
using System.Web;
using System.Web.Mvc;

namespace MS_Toys.Controllers
{
    public class LogInController : Controller
    {
        public LogInController()
        {
            Log.Initialize();
        }

        private StoreDataContext db = new StoreDataContext();

        // GET: LogIn/Create
        public ActionResult Create()
        {
            ViewData["username"] = Cookie.Get(Request, "username");
            return View(new User());
        }

        // POST: LogIn/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Username,EncryptedPassword")] User user)
        {
            var getUser = Data.GetUser(db, user.Username);

            if (getUser == null)
            {
                Trace.WriteLine("User '" + user.Username + "' was not found");
                ViewData["username"] = Cookie.Get(Request, "username");

                return View(user);
            }

            Cookie.UsernameCookie(Response, user);

            ViewData["username"] = user.Username;
            Trace.WriteLine("User '" + user.Username + "' has logged in");

            return Redirect("/Home/Index");
        }

        public ActionResult LogOut()
        {
            /*if (ViewData["username"] == null || ViewData["username"].ToString().Length == 0)
            {
                return View(new User());
            }*/

            // Cookie.Delete(Request, "username");
            // Request.Cookies.Clear();
            // Cookie.Clear(Response, Request, "username");

            // ViewData["username"] = Cookie.Get(Request, "username");

            return Redirect("/Home/Index");
        }
    }
}

MS-Toys/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MS_Toys.Models;
using StoreAdministration;

namespace MS_Toys.Controllers
{
    public class UsersController : Controller
    {
        public UsersController()
        {
            Log.Initialize();
        }

        private StoreDataContext db = new StoreDataContext();

        // GET: Users
        public ActionResult Index()
        {
            ViewData["username"] = Cookie.Get(Request, "username");
            return View(db.Users.ToList());
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewData["username"] = Cookie.Get(Request, "username");
            return View(new User());
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Username,FirstName,LastName,EncryptedPassword")] User user)
        {
            // ViewData["username"] = Cookie.Get(Request, "username");

            if (ModelState.IsValid)
            {
                var users = Data.GetAllUsernames(db);

                foreach (var user_ in users)
                {
                    if (user_.Username == user.Username)
                    {
                        return View(user);
                    }
                }

                Data.SignUserUp(db, user.Username, user.EncryptedPassword, user.FirstName, user.LastName);

                Trace.WriteLine("User '" + user.Username + "' has signed up");

                ViewData["username"] = user.Username;

                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            ViewData["username"] = Cookie.Get(Request, "username");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = db.Users.Find(id);

            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Username,FirstName,LastName,EncryptedPassword")] User user)
        {
            ViewData["username"] = Cookie.Get(Request, "username");

            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                Trace.WriteLine("User '" + user.Username + "' was edited");

                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            ViewData["username"] = Cookie.Get(Request, "username");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = db.Users.Find(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ViewData["username"] = Cookie.Get(Request, "username");

            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            Trace.WriteLine("User '" + user.Username + "' was deleted");

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MS-Toys/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MS-Toys</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MS-Toys", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                    <li>@Html.ActionLink("Transactions", "Index", "Transactions")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Log In", "Create", "LogIn")</li>
                    <li>@Html.ActionLink("Sign Up", "Create", "Users")</li>
                    <li>
                        @Html.ActionLink(
                            ViewData["username"] != null && ViewData["username"].ToString().Length != 0
                            ?
                            ViewData["username"].ToString()
                            : 
                            "[Not logged in]",
                            "LogOut",
                            "LogIn",
                            new { @style = "color: red; !important" }
                        )
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MS-Toys</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>